name: CI

on: push

jobs:

  build:

    # Specifying which OSes to run the tests on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
	python-version: [3.8]

    steps:

    - name: Checkout repository
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
	pip3 install -r requirements.txt
	pip3 install -e .

    - name: Unit Testing with PyTest
      run: |
        pytest --cov=fakes.insert_fakes tests/tests_fakes.py
